[package]
name = "d16"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitreader = "0.3.6"
anyhow={ version = "1.0.57", features = ["backtrace"] }
